fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /sonata_admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata_admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

wrong_router:
    path: /{url}
    defaults: { _controller: AppBundle:Default:wrongRoute }
    requirements:
        url: ".+"