services:
    bcp.usertype:
        class: AppBundle\Form\UserType
        arguments: [%security.role_hierarchy.roles%]

    bcp.external_url_generator:
        class: AppBundle\Utils\ExternalUrlGenerator

    bcp.contact_provider:
        class: AppBundle\Utils\Newsletter\ContactProvider
        arguments:
            - "@doctrine.orm.entity_manager"

    bcp.newsletter:
        class: AppBundle\Utils\Newsletter\NewsletterManager
        arguments:
            - "@bcp.contact_provider"
            - "@templating"
            - %newsletter_from%
            - "@translator"

    bcp.twig_site_pages:
        class: AppBundle\Utils\TwigSitePagesExtension
        arguments: [@doctrine.orm.entity_manager, @security.authorization_checker, @security.token_storage]
        tags:
            - { name: twig.extension }

    bcp.user_mailer:
        class: AppBundle\Utils\MailTransportUserMailer
        arguments:
            - "@router"
            - "@templating"
            - "@translator"
            - { confirmation.template: %fos_user.registration.confirmation.template%, resetting.template: %fos_user.resetting.email.template%, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% } }

    bcp.facebook:
        class: AppBundle\Utils\Facebook\FacebookApplicationManager
        arguments:
            - %fb_app_id%
            - %fb_app_secret%
            - %fb_default_graph_version%
            - %fb_page_id%
            - "@security.token_storage"
            - "@templating.helper.assets"
            - "@router"

    bcp.cookie_consent:
        class: AppBundle\EventListeners\KernelRequestListener
        arguments:
            - "@templating"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: handleCookieConsent }