<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Abstraction\AbstractEntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends AbstractEntityRepository
{
}
