<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Abstraction\AbstractEntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends AbstractEntityRepository
{
    public function getWithArticlePublishedQuery()
    {
        $qb = $this->createQueryBuilder('i')
                   ->leftJoin('i.post', 'p')
                   ->where('p.published = 1')
                   ->orderBy('p.created', 'DESC');

        return $qb->getQuery();
    }

    public function getAllWithArticleQuery()
    {
        $qb = $this->createQueryBuilder('i')
            ->leftJoin('i.post', 'p')
            ->orderBy('p.created', 'DESC');

        return $qb->getQuery();
    }
}
