<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Abstraction\AbstractEntityRepository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends AbstractEntityRepository
{
}
