<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Abstraction\AbstractEntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends AbstractEntityRepository
{
    public function findFully($id)
    {
        $qb = $this->createQueryBuilder('p')
                   ->where('p.id = :id')->setParameter('id', $id)
                   ->leftJoin('p.image', 'i')->addSelect('i')
                   ->leftJoin('p.author', 'a')->addSelect('a');

        try {
            return $qb->getQuery()->getSingleResult();
        } catch(\Exception $e) {
            return null;
        }
    }

    public function findAllOrderByPriorityAndPublished()
    {
        $qb = $this->createQueryBuilder('p')
                   ->where('p.published = 1')
                   ->orderBy('p.priority', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findAllOrderByPriority()
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.priority', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
