<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Abstraction\AbstractEntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends AbstractEntityRepository
{
    public function findFully($id)
    {
        $qb = $this->createQueryBuilder('p')
                   ->where('p.id = :id')->setParameter('id', $id)
                   ->leftJoin('p.images', 'i')->addSelect('i')
                   ->leftJoin('p.pdfs', 'i')->addSelect('pdf')
                   ->leftJoin('p.author', 'a')->addSelect('a');

        try {
            return $qb->getQuery()->getSingleResult();
        } catch(\Exception $e) {
            return null;
        }
    }

    public function getFindAllByCreated()
    {
        $qb = $this->createQueryBuilder('p')
                   ->orderBy('p.created', 'DESC');

        return $qb->getQuery();
    }

    public function getFindLatestQuery()
    {
        $qb = $this->createQueryBuilder('p')
                   ->where('p.published = 1')
                   ->orderBy('p.created', 'DESC');

        return $qb->getQuery();
    }
}
